//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientNotes
    {
        public int IDClientNotes { get; set; }
        public int IDClient { get; set; }
        public string Text { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
