//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourtPrice
    {
        public int IDCourtPrice { get; set; }
        public int IDCourt { get; set; }
        public int IDDay { get; set; }
        public int From { get; set; }
        public int To { get; set; }
        public decimal Price { get; set; }
    
        public virtual Court Court { get; set; }
    }
}
