//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioCliente
    {
        public int IDHorarioCliente { get; set; }
        public int IDCliente { get; set; }
        public int Dia { get; set; }
        public System.DateTime Desde { get; set; }
        public System.DateTime Hasta { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
