//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int IDReserva { get; set; }
        public int IDCancha { get; set; }
        public int IDCliente { get; set; }
        public decimal Precio { get; set; }
        public decimal Reserva1 { get; set; }
        public int IDEstadoReserva { get; set; }
        public string NombreReserva { get; set; }
        public System.DateTime FechaHora { get; set; }
    
        public virtual Cancha Cancha { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoReserva EstadoReserva { get; set; }
    }
}
